/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppManagerRouteImport } from './routes/_app/manager'
import { Route as AppIntelligenceRouteImport } from './routes/_app/intelligence'
import { Route as AppEmployeeRouteImport } from './routes/_app/employee'
import { Route as AppCheckinRouteImport } from './routes/_app/checkin'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppGoalsNewRouteImport } from './routes/_app/goals/new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeRoute = AppEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsNewRoute = AppGoalsNewRouteImport.update({
  id: '/goals/new',
  path: '/goals/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/checkin': typeof AppCheckinRoute
  '/employee': typeof AppEmployeeRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/manager': typeof AppManagerRoute
  '/goals/new': typeof AppGoalsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/checkin': typeof AppCheckinRoute
  '/employee': typeof AppEmployeeRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/manager': typeof AppManagerRoute
  '/goals/new': typeof AppGoalsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/employee': typeof AppEmployeeRoute
  '/_app/intelligence': typeof AppIntelligenceRoute
  '/_app/manager': typeof AppManagerRoute
  '/_app/goals/new': typeof AppGoalsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/admin'
    | '/checkin'
    | '/employee'
    | '/intelligence'
    | '/manager'
    | '/goals/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin'
    | '/checkin'
    | '/employee'
    | '/intelligence'
    | '/manager'
    | '/goals/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/checkin'
    | '/_app/employee'
    | '/_app/intelligence'
    | '/_app/manager'
    | '/_app/goals/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence': {
      id: '/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee': {
      id: '/_app/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AppEmployeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/new': {
      id: '/_app/goals/new'
      path: '/goals/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof AppGoalsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppEmployeeRoute: typeof AppEmployeeRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppManagerRoute: typeof AppManagerRoute
  AppGoalsNewRoute: typeof AppGoalsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppEmployeeRoute: AppEmployeeRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppManagerRoute: AppManagerRoute,
  AppGoalsNewRoute: AppGoalsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
